In [24]:
import math

In [26]:
math.pi

3.141592653589793

In [28]:
math.cos(60)

-0.9524129804151563

In [30]:
import math as m

In [32]:
m.cos(22.5)

-0.8733046400935156

In [34]:
m.log(80)

4.382026634673881

In [36]:
import numpy as np

In [38]:
# 1 dimensional array
arr1=np.array([1,2,3,4,5,5])

In [40]:
print(arr1)

[1 2 3 4 5 5]


In [42]:
type(arr1)

numpy.ndarray

In [44]:
np.int64(3)

3

In [46]:
arr2=np.array([2,5,'True','ok',10.5])

In [60]:
import time
time.time()

1767760210.747766

In [62]:
l=[1,2,3,4,5]
l*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [64]:
arr1*2

array([ 2,  4,  6,  8, 10, 10])

### time difference for list and array

In [81]:
l1=list(range(1,1000000))

In [83]:
print(l1)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [76]:
a=np.array(l1)

### list time: Array took less time as compared to list

In [79]:
start_time=time.time()
newl=[x*2 for x in l1]
end_time=time.time()
time_list=end_time-start_time
print("time taken by list:",time_list)

time taken by list: 0.05063581466674805


In [90]:
start_time=time.time()
newt=a*2
end_time=time.time()
time_array=end_time-start_time
print("time taken:",time_array)

time taken: 0.004686117172241211


In [92]:
time_list/time_array

8.25454082930552

In [94]:
arr1

array([1, 2, 3, 4, 5, 5])

In [96]:
arr1[1:4]

array([2, 3, 4])

# 2 dimensional array

In [99]:
arr=np.array([[1,4,4],[5,2,9],[12,4,78],[0,-1,5]])

In [101]:
arr

array([[ 1,  4,  4],
       [ 5,  2,  9],
       [12,  4, 78],
       [ 0, -1,  5]])

In [103]:
arr.ndim

2

In [105]:
arr.shape

(4, 3)

In [108]:
arr[1:3,0:2]

array([[ 5,  2],
       [12,  4]])

In [112]:
arr[2:3,2:3]

array([[78]])

In [114]:
arr[1:,:2]

array([[ 5,  2],
       [12,  4],
       [ 0, -1]])

In [116]:
arr[1:4:2,0:2:]

array([[ 5,  2],
       [ 0, -1]])

# Specific row number u can give without step

In [128]:
arr[[[0,1,3]],0:2]

array([[[ 1,  4],
        [ 5,  2],
        [ 0, -1]]])

In [136]:
arr[2,2]=100

In [138]:
arr

array([[  1,   4,   4],
       [  5,   2,   9],
       [ 12,   4, 100],
       [  0,  -1,   5]])

In [140]:
arr.reshape(3,4)

array([[  1,   4,   4,   5],
       [  2,   9,  12,   4],
       [100,   0,  -1,   5]])

# Convert any dimension array into 1 dimension using flatten function

In [146]:
arr.flatten()

array([  1,   4,   4,   5,   2,   9,  12,   4, 100,   0,  -1,   5])

# linear algebra

In [161]:
arr=np.array([[1,4,4],[5,2,9],[12,4,78]])

In [163]:
arr

array([[ 1,  4,  4],
       [ 5,  2,  9],
       [12,  4, 78]])

In [165]:
np.linalg.inv(arr)

array([[-0.1171875 ,  0.2890625 , -0.02734375],
       [ 0.27539063, -0.02929688, -0.01074219],
       [ 0.00390625, -0.04296875,  0.01757812]])

In [167]:
np.linalg.det(arr)

-1024.0

In [169]:
np.linalg.eig(arr)

EigResult(eigenvalues=array([79.16931206, -2.79574202,  4.62642996]), eigenvectors=array([[-0.05682631, -0.76237073, -0.65486323],
       [-0.11928606,  0.64199491, -0.74121216],
       [-0.99123237,  0.08144574,  0.14750826]]))

In [183]:
np.transpose(arr)

array([[ 1,  5, 12],
       [ 4,  2,  4],
       [ 4,  9, 78]])

In [185]:
import numpy as np

In [187]:
arr3=np.array([100,200,300])

In [189]:
arr3

array([100, 200, 300])

In [193]:
arr4=np.array([[200,300,400],[500,600,700],[800,900,1000]])

In [195]:
arr4

array([[ 200,  300,  400],
       [ 500,  600,  700],
       [ 800,  900, 1000]])

In [204]:
arr4[0:3,0:2]

array([[200, 300],
       [500, 600],
       [800, 900]])

# Data Analysis with Pandas

In [206]:
# Series= One dimensional datastructure like structure with hiomogeneous data,size immutable,values of data mutable
# Dataframe= 2 Dimensional datastructure -Container for multiple series with heterogeneous data,size mutable,data mutable

In [1]:
import pandas as pd

# Series

In [4]:
s=pd.Series([45,67,23,12,10])

In [6]:
s

0    45
1    67
2    23
3    12
4    10
dtype: int64

In [8]:
s1=pd.Series([200,300])

In [10]:
s1

0    200
1    300
dtype: int64

In [12]:
type(s)

pandas.core.series.Series

In [14]:
s[3]

12

In [16]:
s.shape

(5,)

# You can give manual indexing

In [19]:
s=pd.Series([1,45,78,32,10],index=range(101,106))

In [21]:
s

101     1
102    45
103    78
104    32
105    10
dtype: int64

# Dataframe

In [24]:
roll=pd.Series([1,2,3,4,5])
name=pd.Series(['Ankit','Riya','Natasha','Ranjit','tushar'])
marks=pd.Series([67.56,78.92,67.12,55.78,82.45])

In [26]:
df=pd.DataFrame({'roll':roll,'name':name,'marks':marks})

In [28]:
df

roll     name  marks
0     1    Ankit  67.56
1     2     Riya  78.92
2     3  Natasha  67.12
3     4   Ranjit  55.78
4     5   tushar  82.45

In [30]:
df.size

15

In [32]:
df.columns

Index(['roll', 'name', 'marks'], dtype='object')

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   roll    10 non-null     int64  
 1   name    10 non-null     object 
 2   class   10 non-null     object 
 3   marks   10 non-null     float64
 4   age     10 non-null     int64  
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes


In [63]:
df.describe()

roll      marks        age
count  10.00000  10.000000  10.000000
mean    5.50000  64.499000  20.500000
std     3.02765   9.207179   1.269296
min     1.00000  49.550000  19.000000
25%     3.25000  57.520000  20.000000
50%     5.50000  64.310000  20.000000
75%     7.75000  69.327500  21.000000
max    10.00000  78.660000  23.000000

In [65]:
df.head()

roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [69]:
df.head(3)

roll    name class  marks  age
0     1    anil    TE  56.77   22
1     2    amit    TE  59.77   21
2     3  aniket    BE  76.88   19

In [67]:
df.tail()

roll    name class  marks  age
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [71]:
df

roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [34]:
df=pd.read_csv("student.csv")

In [36]:
df

roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [73]:
#For extracting in one step
df.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20],
       [6, 'ayesha', 'BE', 49.55, 20],
       [7, 'amar', 'BE', 65.34, 19],
       [8, 'amita', 'BE', 68.33, 23],
       [9, 'amol', 'TE', 56.75, 20],
       [10, 'anmol', 'BE', 78.66, 21]], dtype=object)

In [75]:
#Transpose 
df.T

0      1       2        3      4       5      6      7      8  \
roll       1      2       3        4      5       6      7      8      9   
name    anil   amit  aniket  ajinkya   asha  ayesha   amar  amita   amol   
class     TE     TE      BE       TE     TE      BE     BE     BE     TE   
marks  56.77  59.77   76.88    69.66  63.28   49.55  65.34  68.33  56.75   
age       22     21      19       20     20      20     19     23     20   

           9  
roll      10  
name   anmol  
class     BE  
marks  78.66  
age       21

In [ ]:
# Index based slicing iloc fun and loc for Label based slicing

In [78]:
df.iloc[2:5,0:3]

roll     name class
2     3   aniket    BE
3     4  ajinkya    TE
4     5     asha    TE

In [80]:
#list of number of row ,list of number of column
df.iloc[[2,3,5],[0,1,3]]

roll     name  marks
2     3   aniket  76.88
3     4  ajinkya  69.66
5     6   ayesha  49.55

In [86]:
df.iloc[5,1]="geet"

In [88]:
df

roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [38]:
df.shape

(10, 5)

In [44]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [48]:
df1=pd.read_csv("student1.csv")

In [51]:
df1

1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21